# Generated by Django 5.1.6 on 2025-06-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_investment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='profit_paid',
            field=models.BooleanField(default=False),
        ),
    ]
