# Generated by Django 5.1.6 on 2025-06-24 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_investment_profit_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Usage',
                'verbose_name_plural': 'Chat Usage',
                'ordering': ['-timestamp'],
            },
        ),
    ]
